trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - README.md

resources:
  repositories:
  - repository: pipeline-templates
    type: git
    name: GT.ICS-Cloud Planning/vdc-orchestration-pipeline-templates
    ref: master

variables:
- name: scriptsRepoName
  value: $[ resources.repositories['pipeline-templates'].name ]
- name: scriptsRepoRef
  value: $[ resources.repositories['pipeline-templates'].ref ]
- group: TFE-Terratest-KV

extends:
  template: infrastructure/module-pipeline.yaml@pipeline-templates
  parameters:
    tfeToken: $(TFE-TOKEN)
    tfVersion: 1.3.9
    tflintVersion: 0.42.2
    distributedTerratest: false
    moduleProductCategory: tfe-module-core
    majorVersion: 0
    minorVersion: 1
    startingSeed: 0 # One time use for migration to module 2.0 to sync patch version
    poolName: 'CEP-Pool-GF-Prod'
    azureSubscriptionSE: 'Assurant SPOKE VDC Model'