name: Deploy Azure VM with Terraform

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on PR to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '3.0.0'  # Specify the Terraform version you want to use

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

