name: Deploy Azure VM using Terraform

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the 'main' branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # The runner type, can change if necessary

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'  # Specify the version of Terraform you want to use

      # Set up Azure credentials (Service Principal)
      - name: Set up Azure Credentials
        uses: azure/setup-azure-cli@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform configuration (auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve
