name: Deploy Azure VM with Terraform

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on PR to the main branch

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
        
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.3.0'

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform  # Use the correct directory for Terraform files

    - name: Validate Terraform configuration
      run: terraform validate
      working-directory: ./terraform  # Ensure validate is run in the correct directory

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform  # Ensure plan is run in the correct directory

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve
      working-directory: ./terraform  # Ensure apply is run in the correct directory
